import { createElement } from 'lwc';
import EMS_LM_ContactLeaveBalaceComponentRelated from 'c/eMS_LM_ContactLeaveBalaceComponentRelated';

describe('c-e-m-s-l-m-contact-leave-balace-component-related', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-e-m-s-l-m-contact-leave-balace-component-related', {
            is: EMS_LM_ContactLeaveBalaceComponentRelated
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});